on: push
name: Publish Website
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: 192.168.0.200
        remote-user: root
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: /var/www/dev.vb/